- name: Install package list - desktop common
  dnf: name={{item}} state=installed
  with_items:
    - gnome-terminal
    - firefox
    - icecat
    - midori
    - qutebrowser
    - epiphany
    - shotwell
    - evince
    - clementine
    - gnome-keyring
    - gnome-keyring-pam
    - NetworkManager
    - NetworkManager-tui
    - NetworkManager-vpnc
    - NetworkManager-vpnc-gnome
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - ImageMagick
    - ImageMagick-devel
    - transmission
    - transmission-gtk
    - arduino
    - hplip-gui
    - hplip-common
    - hplip-libs
    - levien-inconsolata-fonts
    - terminus-fonts
    - liberation-fonts-common
    - liberation-sans-fonts
    - liberation-mono-fonts
    - liberation-serif-fonts
    - mozilla-fira-mono-fonts
    - msimonson-anonymouspro-fonts
    - adobe-source-code-pro-fonts
    - dejavu-sans-fonts
    - dejavu-serif-fonts
    - dejavu-sans-mono-fonts
    - gnu-free-fonts-common
    - gnu-free-sans-fonts
    - gnu-free-mono-fonts
    - gnu-free-serif-fonts
    - terminus-fonts
    - overpass-fonts
    - fedora-arm-installer
    - virt-top
    - krb5-workstation
    - krb5-auth-dialog
    - gitg
    - gitstats
    - gitflow
    - git-cola
    - git-xcleaner
    - git-cal
    - android-tools
    - libreoffice-writer
    - libreoffice-calc
    - libreoffice-impress
    - libreoffice-draw
    - gimp
    - pinta
    - inkscape
    - icedtea-web
    - RunSnakeRun
    - xsel
    - xclip
    - flatpak
    - flatpak-builder
    - pcp-gui
    - pcp-doc
    - qpdf
    - xournal
    - vagrant
    - vagrant-libvirt
    - vagrant-doc
    - vagrant-libvirt-doc
    - gobby05
    - heimdall
    - meld
    - pidgin
    - pidgin-hangouts
    - purple-hangouts
    - purple-facebook

